// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package mydb

import (
	"database/sql"
)

type Message struct {
	ID         int64        `json:"id"`
	ToUserID   int64        `json:"to_user_id"`
	FromUserID int64        `json:"from_user_id"`
	Content    string       `json:"content"`
	CreateTime sql.NullTime `json:"create_time"`
}

type User struct {
	UserID        int64         `json:"user_id"`
	Name          string        `json:"name"`
	Password      string        `json:"password"`
	FollowCount   sql.NullInt64 `json:"follow_count"`
	FollowerCount sql.NullInt64 `json:"follower_count"`
}

type Video struct {
	VideoID       int64         `json:"video_id"`
	Author        int64         `json:"author"`
	PlayUrl       string        `json:"play_url"`
	CoverUrl      string        `json:"cover_url"`
	FavoriteCount sql.NullInt64 `json:"favorite_count"`
	CommentCount  sql.NullInt64 `json:"comment_count"`
	Title         string        `json:"title"`
	CreatedAt     sql.NullTime  `json:"created_at"`
}
